### ISSUE TITLE
Twitter Media Extractor

### ISSUE THREAD

**Issue by TASnomad** [phantombuster/api-store#107]
**Extract metadata from user medias**

- [x] Code
- [x] Hidden prod version deployed
- [x] Tutorial
  - [x] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [ ] Argument help link
  - [ ] Inline help `(?)` links
- [x] Tests
- [ ] Secret URL shared with beta testers
- [x] Prod version revealed and flagged as new
- [x] Newsletter sent

**Comment by TASnomad** [comment]
# TODO:

Contact API ambassador(s)

**Comment by TASnomad** [comment]
API released
